### ISSUE TITLE
Testing project

### ISSUE THREAD

**Issue by nurullodev** [Clean-Planet/CleanPlanet#38]
@misterpozitiv1607

**Comment by misterpozitiv1607** [comment]
Mansurjon Mo'yd1noff, [18.09.2023 18:29]
District
Driver
Street   Districtga bog'liq  District hal qilinsa ishlidi
Address xam Districtga bog'liq
CarController

Mansurjon Mo'yd1noff, [18.09.2023 18:31]
User      Success

Mansurjon Mo'yd1noff, [18.09.2023 18:33]
Region    Success

**Comment by nurullodev** [comment]
#38 closed
